### ISSUE TITLE
Does not support disco series

### ISSUE THREAD

**Issue by camille-rodriguez** [openstack-charmers/charm-quagga#18]
It would be appropriate to add the support for Disco series, as other charms using quagga do (i.e. charm-neutron-dynamic-routing)

**Comment by ryan-beisner** [comment]
Although #19 added the series, the charm deploy fails in an install hook with:

```
2019-09-05 17:05:51 DEBUG install Traceback (most recent call last):
2019-09-05 17:05:51 DEBUG install   File "/var/lib/juju/agents/unit-quagga-disco-0/charm/hooks/install", line 22, in <module>
2019-09-05 17:05:51 DEBUG install     main()
2019-09-05 17:05:51 DEBUG install   File "/var/lib/juju/agents/unit-quagga-disco-0/.venv/lib/python3.7/site-packages/charms/reactive/__init__.py", line 74, in main
2019-09-05 17:05:51 DEBUG install     bus.dispatch(restricted=restricted_mode)
2019-09-05 17:05:51 DEBUG install   File "/var/lib/juju/agents/unit-quagga-disco-0/.venv/lib/python3.7/site-packages/charms/reactive/bus.py", line 390, in dispatch
2019-09-05 17:05:51 DEBUG install     _invoke(other_handlers)
2019-09-05 17:05:51 DEBUG install   File "/var/lib/juju/agents/unit-quagga-disco-0/.venv/lib/python3.7/site-packages/charms/reactive/bus.py", line 359, in _invoke
2019-09-05 17:05:51 DEBUG install     handler.invoke()
2019-09-05 17:05:51 DEBUG install   File "/var/lib/juju/agents/unit-quagga-disco-0/.venv/lib/python3.7/site-packages/charms/reactive/bus.py", line 181, in invoke
2019-09-05 17:05:51 DEBUG install     self._action(*args)
2019-09-05 17:05:51 DEBUG install   File "/var/lib/juju/agents/unit-quagga-disco-0/charm/reactive/quagga_handlers.py", line 33, in start_quagga
2019-09-05 17:05:51 DEBUG install     quagga.restart_services()
2019-09-05 17:05:51 DEBUG install   File "lib/charm/quagga.py", line 53, in restart_services
2019-09-05 17:05:51 DEBUG install     for service in QUAGGA_SERVICES[ubuntu_release]:
2019-09-05 17:05:51 DEBUG install KeyError: 'disco'
2019-09-05 17:05:51 ERROR juju.worker.uniter.operation runhook.go:132 hook "install" failed: exit status 1
```
